### ISSUE TITLE
Fresco webp

### ISSUE THREAD

**Issue by Dooks123** [NAXAM/fresco-android-binding#1]
First off, what an awesome job you've done with the binding.

Is it possible that you add:
- com.facebook.fresco:webpsupport
- com.facebook.fresco:animated-webp:1.10.0
- com.facebook.fresco:webpsupport:1.10.0

It will be much appreciated

**Comment by tuyen-vuduc** [comment]
@Dooks123 

PRs are very welcome!

Cheers.

**Comment by sureshchouhan2009** [comment]
Hi @Dooks123  
did you get any solution for it?

**Comment by Dooks123** [comment]
@sureshchouhan2009 I resorted to using [Xamarin.Android.UniversalImageLoader](https://www.nuget.org/packages/Xamarin.Android.UniversalImageLoader) which worked amazing.

**Comment by Dooks123** [comment]
Xamarin.Android.UniversalImageLoader works excellent
