### ISSUE TITLE
Proguard Issue

### ISSUE THREAD

**Issue by Dooks123** [NAXAM/fresco-android-binding#2]
I can not seem to get Proguard in Xamarin working with this.

    "can't find referenced class javax.annotation.Nullable"

It compiles without Proguard, but the app size is huge then.

**Comment by tuyen-vuduc** [comment]
Hi @Dooks123,

So, you must keep above class. Have you tried?

Cheers.

**Comment by Dooks123** [comment]
I have and without any luck.
I saw that it should have it's own proguard config included, never got it to work.

**Comment by tuyen-vuduc** [comment]
@Dooks123 Did it work?

**Comment by Dooks123** [comment]
> @Dooks123 Did it work?

Hi @tuyen-vuduc, unfortunately not. This was a long time ago and I have resorted to `UniversalImageLoader` - But even after that - I rewrote the entire app in Android Studio and left Xamarin. Was a very good move on my part. Xamarin was heavy, full of complications, Plain native android in Android Studio just works super well.
